apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vault-serviceaccount.yaml
- vault-rbac.yaml
- vault-config.yaml
- vault-init-script.yaml
- vault-statefulset.yaml
- vault-service.yaml
- vault-route.yaml
- vault-init-job.yaml
