apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = "true"
    }

    disable_mlock = true
    ui            = true
    api_addr      = "http://vault.vault.svc.cluster.local:8200"
