apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rustfs-secret.yaml
- rustfs-pvc.yaml
- rustfs-deployment.yaml
- rustfs-service.yaml
- rustfs-route.yaml
- rhoai-s3-credentials.yaml
