apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
stringData:
  AWS_ACCESS_KEY_ID: "rustfsadmin"
  AWS_SECRET_ACCESS_KEY: "rustfsadmin"
  AWS_S3_BUCKET: "rhoai-models"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_S3_ENDPOINT: "http://rustfs.object-storage.svc.cluster.local:9000"
  AWS_S3_ENDPOINT_URL: "http://rustfs.object-storage.svc.cluster.local:9000"
