apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: object-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
stringData:
  access-key: "rustfsadmin"
  secret-key: "rustfsadmin"
