apiVersion: v1
kind: ServiceAccount
metadata:
  name: install-plan-approver
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: install-plan-approver
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["installplans", "subscriptions"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: install-plan-approver
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: install-plan-approver
subjects:
- kind: ServiceAccount
  name: install-plan-approver
  namespace: openshift-operators
