apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ai-ml-platform-layer
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/pramodmax/2-ai-ml-platform-layer.git
      revision: main
      directories:
      - path: gitops/core/*
      - path: gitops/opt/nfd
      - path: gitops/opt/gpu
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/managed-by: openshift-gitops
        argocd.argoproj.io/sync-wave: '{{ if eq .path.basename "namespaces" }}-20{{ else if eq .path.basename "vault" }}-10{{ else if eq .path.basename "vault-secrets-operator" }}-5{{ else }}0{{ end }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/pramodmax/2-ai-ml-platform-layer.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
        - CreateNamespace=false
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        retry:
          limit: 10
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 5m
