apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kueue-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-jobset-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhsso
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-science-project
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    openshift.io/display-name: "AI/ML Data Science Project"
    openshift.io/description: "Primary data science workspace for AI/ML workloads"
  labels:
    opendatahub.io/dashboard: "true"
